### ISSUE TITLE
Errors when applying special viewmodel settings.

### ISSUE THREAD

**Issue by LordVGames** [a-horsey/horsies-viewmodel-editor#1]
OS version: Windows 10, version 20H2
I've already tried:
- Removing all extracted animations
- Restoring settings files to default, then setting the static anim settings to `y`
- Including and not including bullet tracers/automatic preloading
- Running the `_GENERATE.bat` file as an administrator
- Using and not using the fixed viewmodels mod with the tool

I'm getting errors when enabling the special settings in the viewmodel settings.txt files, such as `Static_attack` and `More_static_idle`.

The following errors occur when applying the viewmodel settings:
```
find: 'time': No such file or directory
find: '/c': No such file or directory
The process tried to write to a nonexistent pipe.
```

The following errors occur when compiling the viewmodels:
```
c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\_horsie's_viewmodel_editor\dev\decompiled_animations_temp\c_engineer_animations.qc :
	ERROR: c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\_horsie's_viewmodel_editor\dev\decompiled_animations_temp\c_engineer_animations.qc(961): - expecting number, got "fadein"
ERROR: Aborted Processing on 'weapons\c_models\c_engineer_animations.mdl'
```

All this occurs with any class' viewmodel settings files.

**Comment by a-horsey** [comment]
Currently working on a pretty big update which also changes the way static settings work.
I'll release it soon and you can let me know if that fixes it. It can also be tested from the other branch.

**Comment by a-horsey** [comment]
Just merged the changes into main.

**Comment by LordVGames** [comment]
Just tried the new version, it now compiles the animations fine!
However, when it's applying the settings, these errors occur now:
```
Applying the settings:
         Applying Scout Settings...
find: '/c': No such file or directory
find: '&::scatterguns': No such file or directory
                &::scatterguns label missing, skipping weapon
find: '/c': No such file or directory
find: '&::doublebarrels': No such file or directory
                &::doublebarrels label missing, skipping weapon
find: '/c': No such file or directory
find: '&::shortstop': No such file or directory
                &::shortstop label missing, skipping weapon
```
It does this with each weapon category, on all classes. This happens regardless if I've done changes to the settings file or not.

**Comment by LordVGames** [comment]
The errors from the previous post still occur on the new version.

I will note that the missing labels errors weren't happening when I initially created the issue. They started occurring after you said to get the newer version after I posted the issue.

**Comment by a-horsey** [comment]
It's normal for them to show up only after the update, as the update changed the way the settings work. Just to make sure, you did change the settings files to the new format, right? Because older ones would definitely not work properly.
If you did, try doing this:

- Go to _dev/batch and open extract_settings.bat with a text editor.
- Delete this entire block of code:
```
 ::check if labels are intact first
set labels_number=0
IF EXIST label_check_temp del label_check_temp >nul
IF EXIST label_check del label_check >nul
findstr /R /C:"\<%settings_label%\>" "%settings_file%" > label_check_temp
find "%settings_label%" "label_check_temp" /c > label_check
FOR /F "tokens=3" %%b in (label_check) do set labels_number=%%b
IF NOT %labels_number%==2 (
	ECHO.		^%settings_label% label duplicate or missing from settings file, skipping weapon...
	goto :process_settings )
```
- Save and try installing again.

That should completely get rid of those errors (without causing other errors), but I'm worried that if something so simple is causing issues for you, it might end up not applying everything correctly. It's a really weird issue that no one else has had so far.

**Comment by a-horsey** [comment]
I actually did some digging and I found this: https://stackoverflow.com/questions/19642548/batch-find-command-not-working
Not the only instance of that happening either.
You can try this to find out if something is messing with the find.exe being used:

- Open a CMD window
- Type (or just copy) this
`for %f in (find.exe) do @echo %~dpfnx$PATH:f`
- Check the result

The result should be something like "C:\Windows\System32\find.exe". If it's not, it means something else you installed might interfere with it (and it points you to exactly what).

**Comment by LordVGames** [comment]
> The result should be something like "C:\Windows\System32\find.exe".

Turns out it was cygwin's find.exe being used (I didn't even know it had it's own!)
Since I lazily put it at the top of the PATH variable list when trying to debug something with it in the past, it was using the find.exe from cygwin, and not windows. Putting windows' paths at the top of the list fixed it, and the batch script works now.
