### ISSUE TITLE
cannot get the editor to affect the game at all

### ISSUE THREAD

**Issue by billw1** [a-horsey/horsies-viewmodel-editor#5]
I've followed the instructions, changed some settings, ran GENERATE.BAT.. everything looks good, but when I go in game there seems to be no change whatsoever. Preloading or not I load into a sv_pure 0 listen server and have all default viewmodels.

Sorry in advance if I'm missing something obvious.

**Comment by a-horsey** [comment]
Are there any errors when installing? Also check your custom folder for a file named __Horsie'sViewmodelEditor.vpk. If it's there try sending it to me so I can take a look.

And just to be clear, you did pick the install option after changing the settings and running generate.bat?

**Comment by billw1** [comment]
No errors. Yeah, installed until it shows the final screen to press any key to quit.
[here's the file it generated](https://drive.google.com/file/d/1YvfD9E5E19iYI0cEBIuT1uDZK6lRv-V1/view?usp=share_link)

**Comment by a-horsey** [comment]
The files generated do seem to be the default viewmodels with no changes, yeah. Pretty weird. I'm gonna need more information to figure this out, can you do a screen recording of you starting generate and installing? Maybe I can spot something. 
Could also first just send me a zip with the settings files you were trying to apply, maybe there's something there.

**Comment by billw1** [comment]
https://streamable.com/djbbv5
[settings.zip](https://github.com/a-horsey/horsies-viewmodel-editor/files/10685649/settings.zip)
I did try with preloading enabled but it conflicted with my config - I already goto tr_walkway when launching TF2. it didnt work with preloading on anyway.

**Comment by a-horsey** [comment]
Alright, everything seems to be fine both in the settings and generating. 
Your issue, I think, is that you didn't set Hidden to Y. It needs to be enabled for the "Keep_X_visible" sub settings to work.

**Comment by billw1** [comment]
Ohh I totally missed that part, thought it was just a header for the section

**Comment by a-horsey** [comment]
Just let me know if everything works after changing so I can close the issue.

**Comment by billw1** [comment]
Yes its working now. thanks
