### ISSUE TITLE
Spy's watches don't work.

### ISSUE THREAD

**Issue by citizenfraud** [a-horsey/horsies-viewmodel-editor#6]
Awesome mod, but spy's watches don't work. Is there any way to make it work?

**Comment by a-horsey** [comment]
If you're talking about there being no settings for the watches, I explained here why it's not possible to implement them: https://github.com/a-horsey/horsies-viewmodel-editor/issues/4#issuecomment-1327482800

**Comment by citizenfraud** [comment]
Sorry for not reading through other issues. Will still be using the mod regardless, thanks!

P.S.
Any way to donate?

**Comment by a-horsey** [comment]
No worries, I should probably explain that in a more visible place.
Yeah you can send me anything on steam with this trade link, but you don't have to: https://steamcommunity.com/tradeoffer/new/?partner=112124325&token=EdZIBC4J
