### ISSUE TITLE
Vote prompt issues

### ISSUE THREAD

**Issue by thevug** [a-horsey/horsies-viewmodel-editor#7]
Hey, 

Since i configured some viewmodels with the viewmodel editor, most of my voting prompts get bugged out. I still get to vote, but it doesn't show options, just an error message. I've only been getting them since using the editor. Could there be any correlation there?

-vug

**Comment by a-horsey** [comment]
Very unlikely. Can try opening generate and installing again just in case. If nothing changes then uninstall and see if it still happens.

**Comment by thevug** [comment]
Will do, thanks for the quick reply.

**Comment by a-horsey** [comment]
I assume this has been solved or is unrelated so I'm closing the issue. Reopen if it's still an issue (and related to the mod).
